swagger: 2.0
info:
  version: "0.0.1"
  title: "Skeleton App"
host: "localhost"
basePath: "/"
schemes:
  - "http"
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
x-volos-resources: {}
paths:
  /forecastrss:
    x-swagger-router-controller: "weather"
    x-volos-authorizations: {}
    x-volos-apply: {}
    get:
      description: "Calls the yahoo weather api"
      operationId: "getForecast"
      produces:
        - "application/json"
      parameters:
        -
          name: "w"
          in: "query"
          description: "Gets weather forecasts for a WOEID"
          required: false
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/WeatherResponse"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  WeatherResponse:
    required:
      - "message"
    properties:
      message:
        type: "string"
        
  ErrorResponse:
    required:
      - "message"
    properties:
      message:
        type: "string"
