swagger: "2.0"
info:
  version: "0.0.1"
  title: A127 Release Notes App
# during dev, should point to your local machine
host: localhost
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
x-a127-config: {}
x-a127-services: {}
paths:
  /owners:
    # binds a127 app logic to a route
    x-swagger-router-controller: owners 
    x-a127-authorizations: {}
    x-a127-apply: {}
    get:
      description: Shows a list of github repo owners of interest to us
      # used as the method name of the controller
      operationId: getOwners
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: OwnersResponse
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: ErrorResponse
  /repos/{owner}:
    # binds a127 app logic to a route
    x-swagger-router-controller: repos 
    x-a127-authorizations: {}
    x-a127-apply: {}
    get:
      description: Returns the repos associated with the owner
      # used as the method name of the controller
      operationId: getRepos
      parameters:
        - name: owner
          in: path
          description: The owner of the rep
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: OwnersResponse
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: ErrorResponse
  repos/{owner}/{repo}/release_notes:
    # binds a127 app logic to a route
    x-swagger-router-controller: notes
    x-a127-authorizations: {}
    x-a127-apply: {}
    get:
      description: Generates release notes for the specified repo 
      # used as the method name of the controller
      operationId: getNotes
      parameters:
        - name: owner 
          in: path
          description: The git repo to query 
          required: false
          type: string
        - name: repo
          in: path
          description: The git repo to query
          required: false
          type: string
        - name: depth
          in: query
          description: The number of releases to compare.
          required: false
          type: number
        - name: save
          in: query
          description: xxxx
          type: string
          required: false
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: ReleaseNotesResponse
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: ErrorResponse
# complex objects have schema definitions
definitions:
  OwnersResponse:
    owners:
      type: object
      properties:
        name:
          type: string
  ReleaseNotesResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
