swagger: "2.0"
info:
  version: "0.0.1"
  title: An API for generating release notes for GitHub releases
host: localhost
basePath: /
# 
schemes:
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
x-a127-config: {}
x-a127-services: {}
paths:
  /accounts:
    x-swagger-router-controller: accounts 
    get:
      description: Shows a list of github user accounts of interest to us
      operationId: getAccounts
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AccountsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /accounts/{account}/repos:
    x-swagger-router-controller: repos
    parameters:
    - name: account
      in: path
      description: Returns information about a specific account
      required: true
      type: string
    get:
      description: Shows a list of github repositories associated with the account
      operationId: getRepos
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AccountsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /accounts/{account}/repos/{repo}:
    parameters:
    - name: account
      in: path
      description: Returns information about a specific account
      required: true
      type: string
    - name: repo
      in: path
      description: The name of the git repository
      type: string
    x-swagger-router-controller: repos
    get:
      description: Returns information about a specific git account
      operationId: getRepo
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AccountsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /accounts/{account}/repos/{repo}/tags:
    x-swagger-router-controller: tags
    parameters:
    - name: account
      in: path
      description: A specific account.
      required: true
      type: string
    - name: repo
      in: path
      description: The name of the git repository
      type: string
    get:
      description: Shows a list of tags associated with an repository.
      operationId: getTags
      responses:
        "200":
          description: Success
          schema: 
            $ref: "#/definitions/AccountsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /accounts/{account}/repos/{repo}/tags/{tag}:
    parameters:
    - name: account
      in: path
      description: A specific account.
      required: true
      type: string
    - name: repo
      in: path
      description: The name of the git repository
      type: string
    - name: tag 
      in: path
      description: A tag number.
      type: string
    x-swagger-router-controller: tags
    get:
      description: Returns information about a specific git tag
      operationId: getTag
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AccountsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /accounts/{account}/repos/{repo}/tags/{tag}/dependencies:
    parameters:
    - name: account
      in: path
      description: Returns information about a specific account
      required: true
      type: string
    - name: repo
      in: path
      description: The name of the git repository
      type: string
    - name: tag
      in: path
      description: The name of the git repository
      type: string
    x-swagger-router-controller: dependencies
    get:
      description: Returns information about a specific git tag
      operationId: getDependencies
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AccountsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /accounts/{account}/repos/{repo}/tags/{tag}/commits:
    parameters:
    - name: account
      in: path
      description: Returns information about a specific account
      required: true
      type: string
    - name: repo
      in: path
      description: The name of the git repository
      type: string
    - name: tag
      in: path
      description: The name of the git repository
      type: string
    x-swagger-router-controller: tags
    get:
      description: Returns information about a specific git tag
      operationId: getCommits
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AccountsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  AccountsResponse:
    owners:
      type: object
      properties:
        name:
          type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
